spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3305/store_api?createDatabaseIfNotExist=true
    username: root
    password: pvhdtnPX#5
  jpa:
    show-sql: true
websiteUrl: http://localhost:3000